In [1]:
import numpy as np


####Be careful when copying arrays:

In [5]:
a=np.array([3,4,5])
b=a
print(b)
b[1]=9
print(a) #the value of a[1] changes as well

[3 4 5]
[3 9 5]


In [7]:
#use copy function:
a=np.array([8,9,0])
b=a.copy()
b[1]=7
print(b)
print(a)

[8 7 0]
[8 9 0]


####MATHEMATICS:

In [10]:
#ARITHMETIC OPERATIONS:
q=np.array([3,5,7])
print(q)

[3 5 7]


In [15]:
q+2



array([5, 7, 9])

In [17]:
q*2

array([ 6, 10, 14])

q-2

In [21]:
q/2

array([1.5, 2.5, 3.5])

In [23]:
#assignment as well:


In [24]:
w=np.array([2,5,8])
q=np.array([3,5,7])
print(w+q)

[ 5 10 15]


In [27]:
#Take the sin,cosin etc
print(np.sin(q))
print(np.cos(q))
print(np.tan(q))

[ 0.14112001 -0.95892427  0.6569866 ]
[-0.9899925   0.28366219  0.75390225]
[-0.14254654 -3.38051501  0.87144798]


#### LINEAR ALGEBRA

In [34]:
e=np.ones((2,3))
print(e)
r=np.full((3,2),2)
print(r)
np.matmul(e,r) #MAKE SURE THE NUMBER OF ROWS=NUMBER OF COLUMNS (i.e here 3=3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [35]:
#For int data type:
e=np.ones((2,3))
print(e)
r=np.full((3,2),2)
print(r)
t=np.matmul(e,r).astype(int)
print(t)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [37]:
#Fnd the deteminant:
y=np.identity(3)
np.linalg.det(y)

np.float64(1.0)

#### Statistics

In [39]:
stats=np.array([[2,3,4],[7,9,3]])
stats

array([[2, 3, 4],
       [7, 9, 3]])

In [41]:
np.min(stats,axis=1)

array([2, 3])

In [42]:
np.max(stats)

np.int64(9)

#### REORGANIZING ARRAYS

In [43]:
before=np.array([[3,4,6,7],[6,3,4,9]])
print(before)
after=before.reshape((8,1)) #should have the same amount of values 
print(after)

[[3 4 6 7]
 [6 3 4 9]]
[[3]
 [4]
 [6]
 [7]
 [6]
 [3]
 [4]
 [9]]


In [45]:
before=np.array([[3,4,6,7],[6,3,4,9]])
after=before.reshape((2,2,2)) #should have the same amount of values 
print(after)

[[[3 4]
  [6 7]]

 [[6 3]
  [4 9]]]


In [46]:
#Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous


In [50]:
# Load data from File

In [54]:
filedata=np.genfromtxt('data.txt',delimiter=',') #delimiter is the seperator(here,comma)
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [55]:
#BOOLEAN MASKING AND ADVANCED INDEXING

In [56]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [57]:
filedata[filedata >50] #grabs only those values which are greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [59]:
#You can index with a list in NumPY:
i=np.array((1,2,3,4,5,6,7,8,9))
i[[1,2,8]]

array([2, 3, 9])

In [60]:
#If any column has a value greater than 50?
np.any(filedata >50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [61]:
#If all the columns have values greater than 50?
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [62]:
#If all the rows have values greater than 50?
np.all(filedata>50,axis=1)

array([False, False, False])

In [63]:
#Giving it some conditions(Boolean masling):
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [65]:
(~(filedata>50) & (filedata<100)) #not greater than 50

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])