In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [7]:
b=np.array([[1.0,2.0,3.0],[5,8,9]])
print(b)

[[1. 2. 3.]
 [5. 8. 9.]]


In [8]:
#Get Dimension
a.ndim

1

In [9]:
b.ndim

2

In [10]:
#Get Shape
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
#Get Type
a.dtype


dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
c=np.array([5,6,8],dtype='int16')
c

array([5, 6, 8], dtype=int16)

In [16]:
c.dtype

dtype('int16')

In [17]:
#Get Size:
a.itemsize

8

In [19]:
c.itemsize

2

In [20]:
#Grt total size
a.size

3

In [22]:
b.size

6

In [23]:
c.size

3

In [25]:
a.nbytes

24

In [26]:
b.nbytes

48

In [27]:
c.nbytes

6

In [28]:
#Get a specific element

In [29]:
e=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
e[1,2]

np.int64(10)

In [33]:
print(np.int64(10))

10


In [34]:
print(e[1,-3])

12


In [35]:
#get a specific row
e[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [37]:
e[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
#get a specific column:
e[:,2]

array([ 3, 10])

In [39]:
e[:,4]

array([ 5, 12])

In [40]:
print(e[:,4])

[ 5 12]


In [41]:
#getting a bit fancy: [row, startindex:endindex:stepsize]
print(e[1, 1:5:2])

[ 9 11]


In [42]:
e[0, 1:-1:2]

array([2, 4, 6])

In [43]:
e[1:3]=23
print(e)

[[ 1  2  3  4  5  6  7]
 [23 23 23 23 23 23 23]]


In [44]:
#To change an element:
e[1,5]=23
print(e)

[[ 1  2  3  4  5  6  7]
 [23 23 23 23 23 23 23]]


In [46]:
e=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
e[1,5]=23
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 23 14]]


In [48]:
#To change a specific column:
e[:,3]=30
print(e)

[[ 1  2  3 30  5  6  7]
 [ 8  9 10 30 12 23 14]]


In [49]:
#or:
e[:,3]=[30,40]
print(e)

[[ 1  2  3 30  5  6  7]
 [ 8  9 10 40 12 23 14]]


In [50]:
#3D example:
f=np.array([[[1,2],[3,4]],[[3,4],[6,9]]])
print(f)


[[[1 2]
  [3 4]]

 [[3 4]
  [6 9]]]


In [51]:
#get the specific element:
print(f[0,1,1])

4


In [52]:
print(f[1,0,0])

3


In [53]:
print(f[:,1,:])

[[3 4]
 [6 9]]


In [54]:
print(f[1,:,1])

[4 9]


In [56]:
#replace:
f[:,1,:]=[[9,9],[8,8]]
print(f)

[[[1 2]
  [9 9]]

 [[3 4]
  [8 8]]]


In [57]:
#Initializing different types of arrays:

In [58]:
#All 0s matrix:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.zeros((2,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [61]:
#All 1s matrix;
np.ones(3)

array([1., 1., 1.])

In [62]:
np.ones(3,dtype='int32')

array([1, 1, 1], dtype=int32)

In [63]:
#Any other matrix:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [64]:
np.full((2,2),5,dtype="float32")

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [65]:
#Any other number(full-like):
np.full_like(e,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [66]:
#Random decimal numbers:
np.random.rand(4,2)

array([[0.87410511, 0.71343534],
       [0.0207217 , 0.40018497],
       [0.16855119, 0.14219657],
       [0.99074414, 0.8435907 ]])

In [67]:
np.random.rand(2,2,3)

array([[[0.68538875, 0.98297592, 0.16754267],
        [0.09771203, 0.90079299, 0.38741099]],

       [[0.19723319, 0.68360584, 0.77382111],
        [0.1154883 , 0.33485284, 0.86206932]]])

In [68]:
#Random integer val
np.random.randint(7,size=(3,3))

array([[1, 0, 3],
       [5, 1, 4],
       [1, 1, 1]], dtype=int32)

In [71]:
np.random.randint(4,7,size=(3,3))

array([[5, 6, 6],
       [4, 6, 4],
       [4, 4, 4]], dtype=int32)

In [73]:
 np.random.randint(0, 10, size=(3, 3)).astype('float64')

array([[5., 1., 8.],
       [7., 7., 4.],
       [1., 3., 9.]])

In [74]:
np.random.randint(-4,7,size=(3,3))

array([[ 1, -2,  1],
       [ 6,  0, -2],
       [ 5,  0, -1]], dtype=int32)

In [75]:
#Identity matrix:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [76]:
#Repeating the array:
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [79]:
arr=np.array([[1,2,3],[5,6,7]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [5 6 7]
 [5 6 7]
 [5 6 7]]


In [87]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
q=np.ones((7,7))
w=np.zeros((3,3))
w[1,1]=5
q[2:5,2:5]=w
r=np.full((2,2),2)
q[0:2,0:2]=r

print(q)


[[2. 2. 1. 1. 1. 1. 1.]
 [2. 2. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 0. 5. 0. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
